import type { Metadata } from "next";
import { Geist, Geist_Mono, Onest } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const onest = Onest({
  variable: "--font-onest",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={onest.variable}>
      <body
        className={`antialiased bg-[#070B0C]`}
      >
        <div className="max-w-[70rem] mx-auto">
          <header className="flex items-center justify-center">
            <Header/>
          </header>
          <main>{children}</main>
          <footer></footer>
        </div>
      </body>
    </html>
  );
}
